### ISSUE TITLE
Tests with non-existing Audit Policy Subcategory fails the whole test.

### ISSUE THREAD

**Issue by canix1** [athaynes/xAuditPolicy#38]
Problem: New operating systems introduce new Audit Policy Subcategories. Running test against older operating systems will fail since the category is missing. The result is no report of compliance.

Expected results: A report with the missing subcategory as "InDesiredState=false".

**Comment by johlju** [comment]
Can you give an example configuration of this? Would help to create a unit test to test this.

**Comment by athaynes** [comment]
@canix1 @johlju @jcwalker SecurityPolicyDsc has a similar functionality with UserRights Assignments now, where they don't throw an error if a SID can't be resolved, but return a warning. Does it make sense to do both? 

For example, if you have a config that sets subcategory named NewSubcategory and NewSubcategory doesn't exist on the target node, then Test-DscConfiguration will return false for that item and we call Write-Warning to provide admin feedback?

The reason we both models originally threw errors was to draw immediate attention to the problem and how to resolve the configuration error.

**Comment by johlju** [comment]
A configuration should be made for the particular target node (with a specific operating system). If the configuration has a subcategory that does not exist on the target node I would expect it to throw. It should throw because that target node can never be in desired state, and if it just write's warnings it
is easy to assume it is in desired state, when it's not. Where can we see the warnings in pull mode?

On the other hand, if a subcategory is not part of the configuration, and the code still tries to evaluate the subcategory from an operating system where the subcategory is not supported (like SecurityPolicyDsc), it should just fail silently, or rather it should not even try to evaluate those subcategories on that operating system if possible.

**Comment by jcwalker** [comment]
@canix1 @athaynes 
@johlju says: "A configuration should be made for the particular target node (with a specific operating system)" If that is the case why is this labeled as an enhancement?  It sounds like it's already operating as intended.  A legacy OS should have a different configuration than the newest OS right?

**Comment by athaynes** [comment]
@johlju @jcwalker I agree that the configuration should be specific to the target node. I personally like for resources to throw a specific error so that I can fix the issue and move on. The reason I didn't want to silently fail was in case someone mistypes a subcategory name. The resource will only evaluate what is explicitly defined, so it is a little different than SecPol in that regard. 

@canix1 Any thoughts on the conversation so far? The current behavior is by design and analogous to trying to define a security policy that doesn't exist. The only real difference is that the valid security policy items are defined in the resource schema. This resource does not define the valid input in the schema to account for the scenario you are describing, but primarily to support localization of auditpol.exe. SecPol has constants defined for each policy item, whereas Auditpol does not.

**Comment by johlju** [comment]
Labeled this 'needs more information' and await response from @canix1.

**Comment by athaynes** [comment]
@canix1 Can you give this branch a try and let m know if it is what you are looking for? https://github.com/PowerShell/AuditPolicyDsc/tree/Issue%2338

**Comment by canix1** [comment]
Ok, I will when I get the chance to. I hardly remember the problem still. But as I remember it now is that the test was not backward compatible and failed. I would expect it to check if the subcategories exist, if not report it as non-compliant.
